name: Okteto deploy

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Okteto Cloud
        uses: okteto/context@2.12.0
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          
      - name: Deploy a preview environment
        uses: okteto/deploy-preview@2.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: staging-${{ github.event.number }}-danielovera
          scope: global
          timeout: 15m
          
      - uses: nev7n/wait_for_response@v1
        with:
          url: https://api-staging-${{ github.event.number }}-danielovera.cloud.okteto.net
          responseCode: 200
          timeout: 4000
  
      - name: Build and deploy application container
        if: ${{ github.event_name == 'push' }}
        uses: okteto/deploy-stack@2.12.0
        with:
          build: true
